import torch
import torch.nn as nn

loss_dict = {"MSE":nn.MSELoss,"Huber":nn.HuberLoss,"CrossEntropy":nn.CrossEntropyLoss,'KLD':nn.KLDivLoss,"MAE":nn.L1Loss}


tvsum_video_dict = {'video_1': 'Vehicle Tire_1',
 'video_2': 'Vehicle Tire_2',
 'video_3': 'Vehicle Tire_3',
 'video_4': 'Vehicle Tire_4',
 'video_5': 'Vehicle Tire_5',
 'video_6': 'Vehicle Unstuck_1',
 'video_7': 'Vehicle Unstuck_2',
 'video_8': 'Vehicle Unstuck_3',
 'video_9': 'Vehicle Unstuck_4',
 'video_10': 'Vehicle Unstuck_5',
 'video_11': 'Grooming an Animal_1',
 'video_12': 'Grooming an Animal_2',
 'video_13': 'Grooming an Animal_3',
 'video_14': 'Grooming an Animal_4',
 'video_15': 'Grooming an Animal_5',
 'video_16': 'Making Sandwich_1',
 'video_17': 'Making Sandwich_2',
 'video_18': 'Making Sandwich_3',
 'video_19': 'Making Sandwich_4',
 'video_20': 'Making Sandwich_5',
 'video_21': 'Parkour_1',
 'video_22': 'Parkour_2',
 'video_23': 'Parkour_3',
 'video_24': 'Parkour_4',
 'video_25': 'Parkour_5',
 'video_26': 'Parade_1',
 'video_27': 'Parade_2',
 'video_28': 'Parade_3',
 'video_29': 'Parade_4',
 'video_30': 'Parade_5',
 'video_31': 'Flash Mob_1',
 'video_32': 'Flash Mob_2',
 'video_33': 'Flash Mob_3',
 'video_34': 'Flash Mob_4',
 'video_35': 'Flash Mob_5',
 'video_36': 'Bee Keeping_1',
 'video_37': 'Bee Keeping_2',
 'video_38': 'Bee Keeping_3',
 'video_39': 'Bee Keeping_4',
 'video_40': 'Bee Keeping_5',
 'video_41': 'Bike tricks_1',
 'video_42': 'Bike tricks_2',
 'video_43': 'Bike tricks_3',
 'video_44': 'Bike tricks_4',
 'video_45': 'Bike tricks_5',
 'video_46': 'Dog Show_1',
 'video_47': 'Dog Show_2',
 'video_48': 'Dog Show_3',
 'video_49': 'Dog Show_4',
 'video_50': 'Dog Show_5'}

summe_video_dict = {'video_1': 'Air_Force_One',
 'video_10': 'Excavators river crossing',
 'video_11': 'Fire Domino',
 'video_12': 'Jumps',
 'video_13': 'Kids_playing_in_leaves',
 'video_14': 'Notre_Dame',
 'video_15': 'Paintball',
 'video_16': 'Playing_on_water_slide',
 'video_17': 'Saving dolphines',
 'video_18': 'Scuba',
 'video_19': 'St Maarten Landing',
 'video_2': 'Base jumping',
 'video_20': 'Statue of Liberty',
 'video_21': 'Uncut_Evening_Flight',
 'video_22': 'Valparaiso_Downhill',
 'video_23': 'car_over_camera',
 'video_24': 'paluma_jump',
 'video_25': 'playing_ball',
 'video_3': 'Bearpark_climbing',
 'video_4': 'Bike Polo',
 'video_5': 'Bus_in_Rock_Tunnel',
 'video_6': 'Car_railcrossing',
 'video_7': 'Cockpit_Landing',
 'video_8': 'Cooking',
 'video_9': 'Eiffel Tower'}